### PR TITLE
Ignore elements with box-header-off when determining epub suitability (BL-11523)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/181)

### CODE REVIEW

**Review by StephenMcConnel — COMMENTED** [review]
The change looks okay.    The description misled me.  Something like "Ignore elements with box-header-off class when determining epub suitability" would be a bit less ambiguous.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/181#-:-NBneS5r0jkdjGXxSa-h:b-r3lod4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Comment by andrew-polk** [comment]
Thanks; fixed

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/181)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions

___
*[`src/Harvester/BookAnalyzer.cs` line 491 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/181#-NBnhAu4AYtqDpgdmV1y:-NBnhAu4AYtqDpgdmV1z:b-d93g7e) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/f9c84b9afa56f44c85cc5d3870a55b78487d2546/src/Harvester/BookAnalyzer.cs#L491)):*
> ```Smalltalk
> 		private IEnumerable<XmlElement> GetNumberedPages() => _dom.SafeSelectNodes("//div[contains(concat(' ', @class, ' '),' numberedPage ')]").Cast<XmlElement>();
> 
> 		private static string GetTranslationGroupsXpath(bool includeImageDescriptions)
> ```

Not a new problem, but without a .// in front, it will only match when applied to page elements (or more specifically, the immediate parent of .marginBox). Could we make that clearer in the name, or at least a comment?? Could either make it clearer what TGs we're trying to omit by excluding box-header-off ones? Imagine for example some new kind of TG...how would someone know whether this method should include it or exclude it?
___
*[`src/Harvester/BookAnalyzer.cs` line 494 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/181#-NBnhs8685RAvvYcCWvK:-NBnhs8685RAvvYcCWvL:bgixbs1) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/f9c84b9afa56f44c85cc5d3870a55b78487d2546/src/Harvester/BookAnalyzer.cs#L494)):*
> ```Smalltalk
> 		{
> 			string imageDescFilter = includeImageDescriptions ? "" : " and not(contains(@class,'bloom-imageDescription'))";
> 			string xPath = $"div[contains(@class,'marginBox')]//div[contains(@class,'bloom-translationGroup') and not(contains(@class, 'box-header-off')){imageDescFilter}]";
> ```

Maybe a comment like, "We no longer use box-header-off for anything, but some older books have it, and for [whatever purpose(s) this method is used] we don't want them to count...they are normally invisible, for one thing."
I don't find any rule anywhere to make the invisible, BTW. Are they just always empty?

**Comment by andrew-polk** [comment]
*[`src/Harvester/BookAnalyzer.cs` line 494 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/181#-NBnhs8685RAvvYcCWvK:-NByKkh3Anlig3wjGFER:b-lin95s) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/f9c84b9afa56f44c85cc5d3870a55b78487d2546/src/Harvester/BookAnalyzer.cs#L494)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe a comment like, "We no longer use box-header-off for anything, but some older books have it, and for [whatever purpose(s) this method is used] we don't want them to count...they are normally invisible, for one thing."
I don't find any rule anywhere to make the invisible, BTW. Are they just always empty?
</blockquote></details>

They are actually stripped from the epub. So it is actually pretty awkward/wrong the way we are determining suitability... : (

I've attempted to improve things in https://github.com/BloomBooks/bloom-harvester/pull/182. See what you think.

**Comment by andrew-polk** [comment]
*[`src/Harvester/BookAnalyzer.cs` line 491 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/181#-NBnhAu4AYtqDpgdmV1y:-NByOCP01cT1vrSZKten:bmk96gd) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/f9c84b9afa56f44c85cc5d3870a55b78487d2546/src/Harvester/BookAnalyzer.cs#L491)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not a new problem, but without a .// in front, it will only match when applied to page elements (or more specifically, the immediate parent of .marginBox). Could we make that clearer in the name, or at least a comment?? Could either make it clearer what TGs we're trying to omit by excluding box-header-off ones? Imagine for example some new kind of TG...how would someone know whether this method should include it or exclude it?
</blockquote></details>

I've attempted to improve things in https://github.com/BloomBooks/bloom-harvester/pull/182. See what you think.

**Pull request merged**
