### PR TITLE
Add HarvestState.Requested to the possible states (BL-8287)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/129)

### CODE REVIEW

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/129)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/HarvesterTests/HarvesterTests.cs, line 366 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/129#-MTHUEikENiewRoxhvJ5:-MTHUEikENiewRoxhvJ6:bec5nnn) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/56d7a0cfab627e79f4632a42e89b7eb2da6e7eb2/src/HarvesterTests/HarvesterTests.cs#L366)):*
> ```
> NewOrUpdatedOnly
> ```
Update this test name too

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/129)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/HarvesterTests/HarvesterTests.cs, line 366 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/129#-MTHUEikENiewRoxhvJ5:-MTHc1Dk3HcZ9Era1La9:b3zwcw5) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/56d7a0cfab627e79f4632a42e89b7eb2da6e7eb2/src/HarvesterTests/HarvesterTests.cs#L366)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> NewOrUpdatedOnly
> ```
Update this test name too
</blockquote></details>

Does this imply that you want the Mode name changed to include Requested?  Logically, this would break any existing scripts.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/129)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @sujeffreyl)

___
*[src/HarvesterTests/HarvesterTests.cs, line 366 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/129#-MTHUEikENiewRoxhvJ5:-MTHeeSN3FjHJLTJHOt5:b-oyedfj) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/56d7a0cfab627e79f4632a42e89b7eb2da6e7eb2/src/HarvesterTests/HarvesterTests.cs#L366)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Does this imply that you want the Mode name changed to include Requested?  Logically, this would break any existing scripts.
</blockquote></details>

OK to change the mode name.

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/129)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel and @sujeffreyl)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/129)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/HarvesterTests/HarvesterTests.cs, line 366 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/129#-MTHUEikENiewRoxhvJ5:-MTHegbO9yU0D08J4ODg:b-xscfw5) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/56d7a0cfab627e79f4632a42e89b7eb2da6e7eb2/src/HarvesterTests/HarvesterTests.cs#L366)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

OK to change the mode name. 
</blockquote></details>

renamed mode to HarvestNeeded (and adjusted test name accordingly)

**Review by sujeffreyl — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/129)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
