### PR TITLE
Enable Harvester to create .bloom files (BL-10673)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/152)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Needs to wait for decision about .bloom extension.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/152#-:-MqynHmF0oP-RUkPyltg:b8di5xk)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/Harvester/Harvester.cs, line 1414 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/152#-MqynTbr5Hj0M61Z2tCx:-MqynTbr5Hj0M61Z2tCy:b-ouhi67) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/903b2ef4316e92c3c8e78e02dc82317498daf316/src/Harvester/Harvester.cs#L1414)):*
> ```
> /dotBloom
> ```
I think this might need some discussion. The .bloomd currently goes into the root. If we still think that was the right decision, then these probably should go there, too.

**Review by StephenMcConnel — COMMENTED** [review]
I think we decided to go ahead with .bloomSource outside of TeamCollection.  This is now waiting for the Bloom PR to be merged.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/152#-:-Mr8nYoR2qBHOFKqXusO:b-1yjrd3)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/Harvester/Harvester.cs, line 1414 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/152#-MqynTbr5Hj0M61Z2tCx:-Mr8nVH32whK7DF3M2cn:b-zijkdz) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/903b2ef4316e92c3c8e78e02dc82317498daf316/src/Harvester/Harvester.cs#L1414)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> /dotBloom
> ```
I think this might need some discussion. The .bloomd currently goes into the root. If we still think that was the right decision, then these probably should go there, too.
</blockquote></details>

I changed this to go to the root as well.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/152)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/Harvester/Harvester.cs, line 1414 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/152#-MqynTbr5Hj0M61Z2tCx:-Mr9WOBT6TZ_HnzJjVti:b-sx3gnh) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/903b2ef4316e92c3c8e78e02dc82317498daf316/src/Harvester/Harvester.cs#L1414)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I changed this to go to the root as well.
</blockquote></details>

I'm not seeing that change.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/152)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/Harvester/Harvester.cs, line 1414 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/152#-MqynTbr5Hj0M61Z2tCx:-MrDPl5K2K1CZB-q3Ear:b-f3qvr1) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/903b2ef4316e92c3c8e78e02dc82317498daf316/src/Harvester/Harvester.cs#L1414)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not seeing that change.
</blockquote></details>

Done.  I forgot to push it.

**Review by andrew-polk — APPROVED** [review]
Approved but not merging.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/152#-:-MrNMm7eD7od_aQUtALv:b-bn2v7b)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by andrew-polk — APPROVED** [review]
Bloom PR merged so merging now.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/152#-:-MrNOsCDBpFC5lvCDF0Z:b-us3g9d)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/152)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/Harvester/Program.cs, line 140 at r3](https://reviewable.io/reviews/bloombooks/bloom-harvester/152#-MrNrPofCkuoSZLN-Bdg:-MrNrPofCkuoSZLN-Bdh:bjnl6s5) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/f722f583e85ce06bd8321c98b07b31c809ce4683/src/Harvester/Program.cs#L140)):*
> ```Smalltalk
> 		public bool SkipUploadBloomDigitalArtifacts { get; set; }
> 
> 		[Option("skipUploadBloomSource", Required = false, Default = false, HelpText = "If true, will prevent the .bloom artifact from being created and uploaded.")]
> ```

.bloomSource



_Code quote:_
```Smalltalk
.bloom
```

**Review by StephenMcConnel — COMMENTED** [review]
I made a couple of minor changes in the process of removing draft status, one to get a test to pass and the other to make a command line argument more consistent.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/152#-:-MrNrWGoCjFyROQnHP6L:bnuj8x8)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/152)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/Harvester/Program.cs, line 140 at r3](https://reviewable.io/reviews/bloombooks/bloom-harvester/152#-MrNrPofCkuoSZLN-Bdg:-MrNrwO52PuNX5EpvHq4:b1xoboi) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/f722f583e85ce06bd8321c98b07b31c809ce4683/src/Harvester/Program.cs#L140)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

.bloomSource
</blockquote></details>

Done.  changed to .bloomSource

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/152)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
