### PR TITLE
Add language location to generated bloomCollection file (BL-12583)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-harvester/195)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-harvester/195)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/Harvester/BookAnalyzer.cs` line 302 at r1](https://reviewable.io/reviews/BloomBooks/bloom-harvester/195#-NahJ2vc-LUqNDGzLbUd:-NahJ2vc-LUqNDGzLbUe:bcykmor) ([raw file](https://github.com/BloomBooks/bloom-harvester/blob/9783a6320cceeaf521e2f5da7ef5d3741701cbe7/src/Harvester/BookAnalyzer.cs#L302)):*
> // This code should work if none of the entity names contains a comma.

Should we try to handle that case?
i.e. if there are more than three segments, we concatenate all of them in the last (country) field?

That will mean the data in the dom is wrong (but it probably would be anyway), but the display should at least be correct.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-harvester/195)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/Harvester/BookAnalyzer.cs` line 302 at r1](https://reviewable.io/reviews/BloomBooks/bloom-harvester/195#-NahJ2vc-LUqNDGzLbUd:-NahuRBS5hcPAhXRkvTy:b-ltubul) ([raw file](https://github.com/BloomBooks/bloom-harvester/blob/9783a6320cceeaf521e2f5da7ef5d3741701cbe7/src/Harvester/BookAnalyzer.cs#L302)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> // This code should work if none of the entity names contains a comma.

Should we try to handle that case?
i.e. if there are more than three segments, we concatenate all of them in the last (country) field?

That will mean the data in the dom is wrong (but it probably would be anyway), but the display should at least be correct.
</blockquote></details>

Done.  But see alternative PR, which could be instead of (or in addition to) this one. https://github.com/BloomBooks/BloomDesktop/pull/6027

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-harvester/195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[`src/Harvester/BookAnalyzer.cs` line 302 at r1](https://reviewable.io/reviews/BloomBooks/bloom-harvester/195#-NahJ2vc-LUqNDGzLbUd:-Nahzck87zH1GLEJy464:bkp20q5) ([raw file](https://github.com/BloomBooks/bloom-harvester/blob/9783a6320cceeaf521e2f5da7ef5d3741701cbe7/src/Harvester/BookAnalyzer.cs#L302)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.  But see alternative PR, which could be instead of (or in addition to) this one. https://github.com/BloomBooks/BloomDesktop/pull/6027
</blockquote></details>

Thanks. I merged the other PR. Any reason to keep this PR as well?

**Comment by StephenMcConnel** [comment]
We decided that the change to BloomDesktop is sufficient.

**Comment by StephenMcConnel** [comment]
We decided that we need to upload the collection settings file for harvester to use, but that this code is needed as a fix for books that haven't uploaded that file.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-harvester/195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
