### PR TITLE
Create Harvester youtrack issues for New or Updated Books (BL-8919)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This sidesteps the current limit of 5 error reports per day maximum.
There is now a limit of 1 report per new/updated book per day, and
5 reports per uploader of new/updated books per day, so there is still
some limits on bug reports per day, but not as strict for new (and
updated) books.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/131)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/131)* status: all files reviewed, 5 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/Harvester/AlertManager.cs, line 12 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/131#-MV2ULfD81ILMeLaSJNJ:-MV2ULfD81ILMeLaSJNK:b-36xxgh) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/0af41b6d8e1c33a257cddf75d2159e3fb8dd071e/src/Harvester/AlertManager.cs#L12)):*
> ```
> TryReportAlerts
> ```
I know this isn't you, but will you update this, please?
___
*[src/Harvester/AlertManager.cs, line 19 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/131#-MV2UyjL9vtmKmVpWxJN:-MV2UyjL9vtmKmVpWxJO:b-2ik36q) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/0af41b6d8e1c33a257cddf75d2159e3fb8dd071e/src/Harvester/AlertManager.cs#L19)):*
> ```
> AlertTimeStamp
> ```
How would you feel about calling this simply `Alert` and changing the linked list to `_alerts`?
___
*[src/Harvester/AlertManager.cs, line 105 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/131#-MV2VJ0qCMh3NFUcPVga:-MV2VJ0qCMh3NFUcPVgb:b-o2uhpx) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/0af41b6d8e1c33a257cddf75d2159e3fb8dd071e/src/Harvester/AlertManager.cs#L105)):*
> ```
> // for new books, but limit for uploader as well as unique books.
> ```
I find this comment slightly confusing. It isn't just "new", right?
I think what you're trying to say here is covered in the larger comment above and this can just be removed?
Or could be simplified to something like
`// silence if more than max per uploader`
___
*[src/Harvester/Parse/Model/BookModel.cs, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/131#-MV2X185-aWXotNjNE_a:-MV2X185-aWXotNjNE_b:b-b4cxep) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/0af41b6d8e1c33a257cddf75d2159e3fb8dd071e/src/Harvester/Parse/Model/BookModel.cs#L45)):*
> ```Smalltalk
> 				this.Uploader = new User(); // needed for Unit tests.
> 				this.Uploader.ObjectId = userId;
> 			}
> ```

I'm not fully understanding what is going on.
At the least, I think we need further comments on exactly why we need special logic for unit tests.
But based on my understanding so far, I am not liking having the special logic here. Do we have other options?
___
*[src/HarvesterTests/AlertManagerTests.cs, line 84 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/131#-MV2WW-6DXKKUMvbi__f:-MV2WW-6DXKKUMvbi__g:by6c8yg) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/0af41b6d8e1c33a257cddf75d2159e3fb8dd071e/src/HarvesterTests/AlertManagerTests.cs#L84)):*
> ```
> HarvestState = "New"
> ```
Can we easily make this two test cases where HarvestState is New or Updated?
I think the logic is the same?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/131)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/Harvester/AlertManager.cs, line 12 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/131#-MV2ULfD81ILMeLaSJNJ:-MV3QqRu7EWYdBAbTFca:b-896fix) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/0af41b6d8e1c33a257cddf75d2159e3fb8dd071e/src/Harvester/AlertManager.cs#L12)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> TryReportAlerts
> ```
I know this isn't you, but will you update this, please?
</blockquote></details>

Done.
___
*[src/Harvester/AlertManager.cs, line 19 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/131#-MV2UyjL9vtmKmVpWxJN:-MV3R5nY133aN564-ScB:b-896fix) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/0af41b6d8e1c33a257cddf75d2159e3fb8dd071e/src/Harvester/AlertManager.cs#L19)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> AlertTimeStamp
> ```
How would you feel about calling this simply `Alert` and changing the linked list to `_alerts`?
</blockquote></details>

Done.
___
*[src/Harvester/AlertManager.cs, line 105 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/131#-MV2VJ0qCMh3NFUcPVga:-MV3S2WN8ngpw534Kyee:b-3za41u) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/0af41b6d8e1c33a257cddf75d2159e3fb8dd071e/src/Harvester/AlertManager.cs#L105)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> // for new books, but limit for uploader as well as unique books.
> ```
I find this comment slightly confusing. It isn't just "new", right?
I think what you're trying to say here is covered in the larger comment above and this can just be removed?
Or could be simplified to something like
`// silence if more than max per uploader`
</blockquote></details>

edited the comment
___
*[src/Harvester/Parse/Model/BookModel.cs, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/131#-MV2X185-aWXotNjNE_a:-MV3RCjW8EfE335QgVGh:btrxutd) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/0af41b6d8e1c33a257cddf75d2159e3fb8dd071e/src/Harvester/Parse/Model/BookModel.cs#L45)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not fully understanding what is going on.
At the least, I think we need further comments on exactly why we need special logic for unit tests.
But based on my understanding so far, I am not liking having the special logic here. Do we have other options?
</blockquote></details>

I changed the unit tests to initialize from JSON to avoid needing to change the constructor.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/131)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/131)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/HarvesterTests/AlertManagerTests.cs, line 84 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/131#-MV2WW-6DXKKUMvbi__f:-MV3g8Pj5ygVlSpGYcV6:bewy28b) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/0af41b6d8e1c33a257cddf75d2159e3fb8dd071e/src/HarvesterTests/AlertManagerTests.cs#L84)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> HarvestState = "New"
> ```
Can we easily make this two test cases where HarvestState is New or Updated?
I think the logic is the same?
</blockquote></details>

Done.  Actually I made this four test cases...

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/131)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/131)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
