### PR TITLE
Preserve xmatter settings from book. (BL-9084)

### PR DESCRIPTION
**Pull request by sujeffreyl**
Depends on this BloomDesktop PR: https://github.com/BloomBooks/BloomDesktop/pull/4046

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/120)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/120)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by andrew-polk** [comment]
Question in card: https://issues.bloomlibrary.org/youtrack/issue/BL-9084

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Question in card: https://issues.bloomlibrary.org/youtrack/issue/BL-9084

**Review by sujeffreyl — COMMENTED** [review]
Responded. You can check if it looks OK. Also, backed out the major version change until we test the card.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/120#-:-MKjhAcE3p55gdZOuEPm:b-rzkthi)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
