### PR TITLE
Handle longer filenames inside book folders (BH-5988)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/151)

### CODE REVIEW

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/151)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/Harvester/Harvester.cs, line 190 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/151#-MqufSssENRUvQTItTKh:-Mqul_KO3_08ropMt-kU:b-rluk6u) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/8221ed9772c8a4d59e7702b19e7d2718a660a68f/src/Harvester/Harvester.cs#L190)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

As I understand it, this will also affect the parse column harvesterID.
I think it is pretty useful to have the machine name there. 
Should we add the machine name back there?
Or use something other than `identifier` for the path?
Or have two different properties?
Or?
</blockquote></details>

I changed to using parseDBEnvironment.ToString() in the paths.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/151)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/151)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/Harvester/Harvester.cs, line 1350 at r2](https://reviewable.io/reviews/bloombooks/bloom-harvester/151#-MquyvKsDu1a2xKOZZg7:-MquyvKsDu1a2xKOZZg8:b-u6s25l) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/4a0101606f7f437f1669afa9e3667575dda84d5a/src/Harvester/Harvester.cs#L1350)):*
> ```Smalltalk
> 			//       But for now, the benefit of having each run download into a predictable location (allows caching when enabled)
> 			//       seems to outweigh the cost (since we don't normally run multiple instances w/the same env on same machine)
> 			return Path.Combine(GetRootPath(), "BloomHarvester", _parseDBEnvironment.ToString());
> ```

I was about to merge this and then had the thought... Is this now going to cause all the books to get redownloaded because harvester won't find them in the expected cache location? Do we need to move or copy the existing cache before merging this?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/151)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/Harvester/Harvester.cs, line 1350 at r2](https://reviewable.io/reviews/bloombooks/bloom-harvester/151#-MquyvKsDu1a2xKOZZg7:-Mqv-0ir0vgGGcJGgsUW:b3qna1h) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/4a0101606f7f437f1669afa9e3667575dda84d5a/src/Harvester/Harvester.cs#L1350)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I was about to merge this and then had the thought... Is this now going to cause all the books to get redownloaded because harvester won't find them in the expected cache location? Do we need to move or copy the existing cache before merging this?
</blockquote></details>

Nothing will force redownloading a book unless a reharvesting is requested.  I can take care of copying/moving the downloaded books at the same time I install the new harvester for dev and for for prod.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/151)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[src/Harvester/Harvester.cs, line 1350 at r2](https://reviewable.io/reviews/bloombooks/bloom-harvester/151#-MquyvKsDu1a2xKOZZg7:-MqvGHR5ByvAGy23d_6U:btmmoy6) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/4a0101606f7f437f1669afa9e3667575dda84d5a/src/Harvester/Harvester.cs#L1350)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Nothing will force redownloading a book unless a reharvesting is requested.  I can take care of copying/moving the downloaded books at the same time I install the new harvester for dev and for for prod.
</blockquote></details>

Ok, merging.

**Pull request merged**
