### PR TITLE
Use the uploaded collection settings file if available (BL-12583)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/Harvester/BookAnalyzer.cs` line 390 at r1](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196#-Nb0X77N6exRTzkXHiA7:-Nb0X77N6exRTzkXHiA8:b3dzojq) ([raw file](https://github.com/BloomBooks/bloom-harvester/blob/27d18207d23108e6d03837d5bb38961f9ebf7174/src/Harvester/BookAnalyzer.cs#L390)):*
> ```Smalltalk
> 				RobustFile.WriteAllText(tempSettingsPath, BloomCollection, Encoding.UTF8);
> 			}
> 			return tempSettingsPath;
> ```

For what will become the normal case -- having the uploaded collection file -- do we even need to populate the BloomCollection object anymore?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/Harvester/BookAnalyzer.cs` line 390 at r1](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196#-Nb0X77N6exRTzkXHiA7:-NbG-p6wAiNEjWpGlctD:bb8g6ty) ([raw file](https://github.com/BloomBooks/bloom-harvester/blob/27d18207d23108e6d03837d5bb38961f9ebf7174/src/Harvester/BookAnalyzer.cs#L390)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

For what will become the normal case -- having the uploaded collection file -- do we even need to populate the BloomCollection object anymore?
</blockquote></details>

There are a couple of variables from the collection settings that are used elsewhere in the code.  I've revised things to make all the code changes in the constructor, setting the variables that can be used elsewhere from the uploaded settings file content if available, and not bothering to search the dom or metadata file for the other values that are used only to populate the generated collection settings.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/Harvester/BookAnalyzer.cs` line 390 at r1](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196#-Nb0X77N6exRTzkXHiA7:-NbG24dgEke9QwMwug1L:b-jljwmm) ([raw file](https://github.com/BloomBooks/bloom-harvester/blob/27d18207d23108e6d03837d5bb38961f9ebf7174/src/Harvester/BookAnalyzer.cs#L390)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

There are a couple of variables from the collection settings that are used elsewhere in the code.  I've revised things to make all the code changes in the constructor, setting the variables that can be used elsewhere from the uploaded settings file content if available, and not bothering to search the dom or metadata file for the other values that are used only to populate the generated collection settings.
</blockquote></details>

Cool. Thanks.

But see new questions.
___
*[`src/Harvester/BookAnalyzer.cs` line 65 at r2](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196#-NbG48nZ4PasCyYDByCH:-NbG48nZ4PasCyYDByCI:bcg3q3) ([raw file](https://github.com/BloomBooks/bloom-harvester/blob/8168d6070d5f883bc29e8cb3e798a011178d596c/src/Harvester/BookAnalyzer.cs#L65)):*
> ```Smalltalk
> 				xdoc.LoadXml(BloomCollection);
> 				Language1Code = xdoc.SelectSingleNode("/Collection/Language1Iso639Code")?.InnerText ?? "";
> 				_bookshelf = xdoc.SelectSingleNode("/Collection/DefaultBookTags")?.InnerText ?? "";
> ```

It doesn't seem safe to assume that if a bookshelf exists that it will always be the only thing in DefaultBookTags.
(If it IS safe, let's add a comment since the label is misleading.)
___
*[`src/Harvester/BookAnalyzer.cs` line 70 at r2](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196#-NbG5aMHEtGpBHq1t95_:-NbG5aMHEtGpBHq1t95a:b9xzxjy) ([raw file](https://github.com/BloomBooks/bloom-harvester/blob/8168d6070d5f883bc29e8cb3e798a011178d596c/src/Harvester/BookAnalyzer.cs#L70)):*
> ```Smalltalk
> 			{
> 				Language1Code = GetBestLangCode(1) ?? "";
> 				Language2Code = GetBestLangCode(2) ?? "en";
> ```

My pessimism is telling me we are asking for trouble if we only populate some of these public properties on one path.
I.e. somewhere we won't realize we did that and we'll add code to consume a potentially unpopulated property. (That seems even more likely if we only have unit tests for the second code path. And it may be worth adding at least one unit test for the new file-exists path.)

It seems like the ideal would be to make them local variables.
Unfortunately, that would mean non-trivial changes to the existing unit tests. I'm not thinking of a better option than extracting this skeleton BloomCollection logic out to method which can be tested directly.

On the other hand, if you think my pessimism deserves a sanity check, feel free to push back.
___
*[`src/Harvester/BookAnalyzer.cs` line 409 at r2](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196#-NbG4axt8uA-wzbebfTL:-NbG4axt8uA-wzbebfTM:b-n95m3g) ([raw file](https://github.com/BloomBooks/bloom-harvester/blob/8168d6070d5f883bc29e8cb3e798a011178d596c/src/Harvester/BookAnalyzer.cs#L409)):*
> The content appropriate to a skeleton BookCollection file for this book.

We should enhance this comment to explain that it will be actual content if possible, else a generated skeleton.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/Harvester/BookAnalyzer.cs` line 65 at r2](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196#-NbG48nZ4PasCyYDByCH:-NbGB2qt-WwDLSJZPdIE:b-ujhdrl) ([raw file](https://github.com/BloomBooks/bloom-harvester/blob/8168d6070d5f883bc29e8cb3e798a011178d596c/src/Harvester/BookAnalyzer.cs#L65)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It doesn't seem safe to assume that if a bookshelf exists that it will always be the only thing in DefaultBookTags.
(If it IS safe, let's add a comment since the label is misleading.)
</blockquote></details>

Done.  I've added code to extract exactly the bookshelf from the tags.
___
*[`src/Harvester/BookAnalyzer.cs` line 70 at r2](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196#-NbG5aMHEtGpBHq1t95_:-NbGQKtZCYLBLbZ0gABO:bbphst4) ([raw file](https://github.com/BloomBooks/bloom-harvester/blob/8168d6070d5f883bc29e8cb3e798a011178d596c/src/Harvester/BookAnalyzer.cs#L70)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

My pessimism is telling me we are asking for trouble if we only populate some of these public properties on one path.
I.e. somewhere we won't realize we did that and we'll add code to consume a potentially unpopulated property. (That seems even more likely if we only have unit tests for the second code path. And it may be worth adding at least one unit test for the new file-exists path.)

It seems like the ideal would be to make them local variables.
Unfortunately, that would mean non-trivial changes to the existing unit tests. I'm not thinking of a better option than extracting this skeleton BloomCollection logic out to method which can be tested directly.

On the other hand, if you think my pessimism deserves a sanity check, feel free to push back.
</blockquote></details>

Done.  I refuse to write new unit tests as long as I cannot run any existing unit tests on my system.  I always get "Could not load file or assembly 'BloomHarvester, ...' or one of its dependencies. An attempt was made to load a program with an incorrect format."
___
*[`src/Harvester/BookAnalyzer.cs` line 409 at r2](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196#-NbG4axt8uA-wzbebfTL:-NbGBTq_23XoRDIdmuMW:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-harvester/blob/8168d6070d5f883bc29e8cb3e798a011178d596c/src/Harvester/BookAnalyzer.cs#L409)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> The content appropriate to a skeleton BookCollection file for this book.

We should enhance this comment to explain that it will be actual content if possible, else a generated skeleton.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[`src/Harvester/BookAnalyzer.cs` line 70 at r2](https://reviewable.io/reviews/BloomBooks/bloom-harvester/196#-NbG5aMHEtGpBHq1t95_:-NbGettd0XoObct9c1uH:b-ut441k) ([raw file](https://github.com/BloomBooks/bloom-harvester/blob/8168d6070d5f883bc29e8cb3e798a011178d596c/src/Harvester/BookAnalyzer.cs#L70)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.  I refuse to write new unit tests as long as I cannot run any existing unit tests on my system.  I always get "Could not load file or assembly 'BloomHarvester, ...' or one of its dependencies. An attempt was made to load a program with an incorrect format."
</blockquote></details>

Ah, you chose the other route of setting them for both paths.

Certainly you can't write (or modify) tests if you can't run them! Let's see if we can figure out what's going on.

**Pull request merged**
