### PR TITLE
Fix a crash computing perceptual hash values (BH-5984)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/149)

### CODE REVIEW

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/149)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel and @sujeffreyl)

___
*[src/Harvester/BookAnalyzer.cs, line 522 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/149#-MqL9Je-34l5JcBFWOqM:-MqL9Je060V3ydlFg42m:b-acpl36) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/ee0bd132c2ca3054431ef6b8126ab6cde10916d0/src/Harvester/BookAnalyzer.cs#L522)):*
> ```Smalltalk
> 			using (var image = (Image<Rgba32>)Image.Load(path))
> 			{
> 				// Corrupt Exif Metadata Orientation values can crash the phash implementation.
> ```

How about putting this stuff in a method called SanitizeImage or FixImage or something along that train of thought?
___
*[src/Harvester/BookAnalyzer.cs, line 529 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/149#-MqL9X456i5OwOqhPI_Z:-MqL9X456i5OwOqhPI__:bpe28v) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/ee0bd132c2ca3054431ef6b8126ab6cde10916d0/src/Harvester/BookAnalyzer.cs#L529)):*
> ```Smalltalk
> 					// An exception is thrown if the value is greater than 65545 (0xFFFF).
> 					var orient = (uint)orientObj.Value;
> 					if ((orient & 0xFFFF) != orient)
> ```

I think (orient > 0xFFFF) (maybe w/some casts to uint) is equivalent and more direct/easily understandable. Is that true?
___
*[src/Harvester/BookAnalyzer.cs, line 535 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/149#-MqL9mECCn70dah5wHao:-MqL9mECCn70dah5wHap:b-mb2z2m) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/ee0bd132c2ca3054431ef6b8126ab6cde10916d0/src/Harvester/BookAnalyzer.cs#L535)):*
> ```Smalltalk
> 						if (orient == 0)
> 							orient = 1;
> 						else if (orient > 9)
> ```

Optional - I think you could use Math.max/Math.min if you prefer. (may need some casting to uint).  This is fine with me too though if you prefer this.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/149)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/Harvester/BookAnalyzer.cs, line 522 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/149#-MqL9Je-34l5JcBFWOqM:-MqLCEhH24BlXMVOF4b9:b-896fix) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/ee0bd132c2ca3054431ef6b8126ab6cde10916d0/src/Harvester/BookAnalyzer.cs#L522)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

How about putting this stuff in a method called SanitizeImage or FixImage or something along that train of thought?
</blockquote></details>

Done.
___
*[src/Harvester/BookAnalyzer.cs, line 529 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/149#-MqL9X456i5OwOqhPI_Z:-MqLEQtb8v3R9F41QQ_3:b-896fix) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/ee0bd132c2ca3054431ef6b8126ab6cde10916d0/src/Harvester/BookAnalyzer.cs#L529)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I think (orient > 0xFFFF) (maybe w/some casts to uint) is equivalent and more direct/easily understandable. Is that true?
</blockquote></details>

Done.
___
*[src/Harvester/BookAnalyzer.cs, line 535 at r1](https://reviewable.io/reviews/bloombooks/bloom-harvester/149#-MqL9mECCn70dah5wHao:-MqLEX1JAQUgrCoUdw13:b-896fix) ([raw file](https://github.com/bloombooks/bloom-harvester/blob/ee0bd132c2ca3054431ef6b8126ab6cde10916d0/src/Harvester/BookAnalyzer.cs#L535)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Optional - I think you could use Math.max/Math.min if you prefer. (may need some casting to uint).  This is fine with me too though if you prefer this.
</blockquote></details>

Done.

**Review by sujeffreyl — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/149)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by sujeffreyl — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-harvester/149#-:-MqLUqj6ElY8-ehmewCy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
